# Generated by Django 3.0.5 on 2021-08-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.CharField(default='compay', max_length=50),
        ),
    ]
