# Generated by Django 3.0.5 on 2021-08-22 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_experience_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='todate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
