# Generated by Django 3.0.5 on 2021-08-22 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_auto_20210821_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='fromdate',
            field=models.CharField(default=datetime.datetime.now, max_length=20),
        ),
    ]
