# Generated by Django 3.0.5 on 2021-08-22 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_auto_20210821_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='fromdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
