# Generated by Django 3.0.5 on 2021-08-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0012_auto_20210821_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='fromdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='todate',
            field=models.DateField(),
        ),
    ]
