# Generated by Django 3.0.5 on 2021-08-22 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0013_auto_20210821_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='fromdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='experience',
            name='todate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
