# Generated by Django 3.0.5 on 2021-08-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0014_auto_20210822_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='fromdate',
            field=models.DateField(verbose_name='%d-%m-%Y'),
        ),
    ]
