# Generated by Django 3.0.5 on 2021-08-22 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0015_auto_20210822_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='fromdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
