# Generated by Django 3.0.5 on 2021-08-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0017_experience_present'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('field', models.CharField(max_length=50)),
            ],
        ),
    ]
