# Generated by Django 3.0.5 on 2021-08-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0020_auto_20210822_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(default='compay', max_length=50),
        ),
    ]
