# Generated by Django 3.0.5 on 2021-09-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0022_remove_photo_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=50)),
            ],
        ),
    ]
