# Generated by Django 3.0.5 on 2021-09-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0023_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='title',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
