# Generated by Django 3.0.5 on 2021-09-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0024_personal_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
