# Generated by Django 3.0.5 on 2021-09-10 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0025_auto_20210910_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='title',
        ),
    ]
