# Generated by Django 3.0.5 on 2021-09-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0027_personal_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
