# Generated by Django 3.0.5 on 2021-09-10 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0028_personal_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='graduation',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
