# Generated by Django 3.0.5 on 2021-09-10 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0030_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='dateissued',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
