# Generated by Django 3.0.5 on 2021-09-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0032_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=1000000),
        ),
    ]
