# Generated by Django 3.0.5 on 2021-09-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0033_auto_20210912_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_skill', models.CharField(max_length=50)),
            ],
        ),
    ]
