# Generated by Django 3.0.5 on 2021-09-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0034_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, max_length=1000000, null=True),
        ),
    ]
