# Generated by Django 3.0.5 on 2021-09-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0035_experience_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(max_length=1000000),
        ),
    ]
